# This file strictly follows the rules defined in the Ruby style guide:
#   http://shopify.github.io/ruby-style-guide/

require: 'rubocop-sorbet'

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  NewCops: disable
  SuggestExtensions: false
  Exclude:
  - 'vendor/**/*'

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true

Layout/LineLength:
  Max: 120
  AllowedPatterns: ['\A\s*#:']

Sorbet:
  Enabled: true

Sorbet/ValidSigil:
  Enabled: true

Sorbet/TrueSigil:
  Enabled: true

Sorbet/EnforceSigilOrder:
  Enabled: true
