name: spoom

type: ruby

up:
  - ruby
  - bundler

commands:
  typecheck:
    aliases: [ "tc" ]
    run:     "bin/typecheck"
  console:   "bin/console"
  test:      "bin/test"
  style:     "bin/style"
  sanity:    "bin/typecheck && bin/style && bin/test"
