cfg: <main>

  bb#0
    class Foo
    -> bb#1

  bb#1

cfg: Foo::<static-init>

  bb#0
    <self>.puts("foo")
    class Bar
    <self>.puts("/foo")
    -> bb#1

  bb#1

cfg: Bar::<static-init>

  bb#0
    <self>.puts("bar")
    class << self
    <self>.puts("/bar")
    -> bb#1

  bb#1

cfg: class << self::<static-init>

  bb#0
    <self>.puts("self")
    def foo
    <self>.private(def bar; end)
    <self>.puts("/self")
    -> bb#1

  bb#1

cfg: foo

  bb#0
    -> bb#1

  bb#1

cfg: bar

  bb#0
    -> bb#1

  bb#1
