name: Release Gem

on:
  push:
    branches:
      - add-push-gem-workflow

permissions:
  contents: read

jobs:
  release_gem:
    if: github.repository == 'shopify/spoom'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - uses: rubygems/configure-rubygems-credentials@v1.0.0

      - run: git tag
